Report v2 changes
get-focus/deprecated-focus-components-v3 pull request #67
Opened 2017-01-04 10:44 UTC by GuenoleK

## Report v2 changes

### Description

> Fixes #49

2017-01-06 13:21 UTC, TomGallon requested changes

2017-01-06 13:21 UTC, TomGallon commented on src/select-mdl/index.js
> +            currentDataVal = 'YOLO';
what is that ?

2017-01-06 13:21 UTC, TomGallon commented on src/select-mdl/index.js
> +            currentDataVal = 'YOLO';
Be careful this code is also written in the previous PR...

2017-01-10 14:50 UTC, Ephrame approved these changes

2017-01-19 10:08 UTC, TomGallon approved these changes

2017-01-19 10:08 UTC, merged